id: 58208c6f55214be196134316fe4f49da
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_103-The_Teaching_by_the_Child_Inconceivable_Radiance-v2
  language: en-us
  author: ''
  volume: {}
